void	writepcm(char*);
void	update(void);
void	setzoom(int, int);
void	setpan(int);
void	setloop(vlong);
void	setpos(vlong);
void	setofs(vlong);
void	redraw(void);
void	initdrw(void);
void*	emalloc(ulong);
